version: '3.8'

services:

  fastapi:
      build:
        context: .
        dockerfile: Dockerfile.fastapi
      container_name: 'bookshelf_fastapi'
      # restart: unless-stopped
      ports:
        - "8000:8000"
      depends_on:
        - db

  grpc:
      build:
        context: .
        dockerfile: Dockerfile.grpc
      container_name: 'bookshelf_grpc'
      # restart: unless-stopped
      ports:
        - "50051:50051"
      depends_on:
        - fastapi

  db:
      image: postgres:15
      container_name: 'bookshelf_db'
      restart: unless-stopped
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
