# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\x05\x62ooks\" \n\x12GetBookByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x12\n\x10ListBooksRequest\"K\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x18\n\x10publication_date\x18\x04 \x01(\t\"/\n\x11ListBooksResponse\x12\x1a\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x0b.books.Book2\x84\x01\n\x0b\x42ookService\x12\x35\n\x0bGetBookById\x12\x19.books.GetBookByIdRequest\x1a\x0b.books.Book\x12>\n\tListBooks\x12\x17.books.ListBooksRequest\x1a\x18.books.ListBooksResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETBOOKBYIDREQUEST']._serialized_start=21
  _globals['_GETBOOKBYIDREQUEST']._serialized_end=53
  _globals['_LISTBOOKSREQUEST']._serialized_start=55
  _globals['_LISTBOOKSREQUEST']._serialized_end=73
  _globals['_BOOK']._serialized_start=75
  _globals['_BOOK']._serialized_end=150
  _globals['_LISTBOOKSRESPONSE']._serialized_start=152
  _globals['_LISTBOOKSRESPONSE']._serialized_end=199
  _globals['_BOOKSERVICE']._serialized_start=202
  _globals['_BOOKSERVICE']._serialized_end=334
# @@protoc_insertion_point(module_scope)
